# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool: 'AWS'

steps:
- task: GoTool@0
  inputs:
    version: '1.14'
  displayName: INstall GO


- task: Go@0
  inputs:
    command: 'get'
    arguments: 'github.com/instana/go-sensor'
  displayName: INstall GO Dependecies Instana

- task: Go@0
  inputs:
    command: 'get'
    arguments: 'github.com/streadway/amqp'
  displayName: Install GO Dependencies Streadway

- task: Go@0
  inputs:
    command: 'get'
    arguments: 'golang.org/x/lint/golint'
  displayName: Install GO Dependencies Lint

- script: |
    ~/go/bin/golint src/main.go
  displayName: 'Go Lint'

- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: 'src'

- task: CmdLine@2
  inputs:
    script: |
      cd src
      mkdir publish
      mv src publish/$(appName)
      cd publish
      az artifacts universal publish --organization https://dev.azure.com/DevOps-Batches/ --project="DevOps48" --scope project --feed RoboShop --name  $(appName) --version 1.0.$(Build.BuildId) --description "$(appName)" --path .
  displayName: Publish Artifacts

variables:
  appName: "dispatch"