# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: GoTool@0
  inputs:
    version: '1.14'


- task: Go@0
  inputs:
    command: 'get'
    arguments: 'github.com/instana/go-sensor'


- task: Go@0
  inputs:
    command: 'get'
    arguments: 'go get github.com/streadway/amqp'
  name: 